SET GLOBAL local_infile = 1;

CREATE DATABASE IF NOT EXISTS retail_analytics;
USE retail_analytics;

CREATE TABLE online_retail_clean (
    InvoiceNo VARCHAR(20),
    StockCode VARCHAR(20),
    Description TEXT,
    Quantity INT,
    InvoiceDate DATETIME,
    UnitPrice DECIMAL(10,2),
    CustomerID INT,
    Country VARCHAR(50),
    TotalAmount DECIMAL(12,2),
    Year INT,
    Month INT
);

SHOW VARIABLES LIKE 'local_infile';

LOAD DATA LOCAL INFILE 'D:/Projects/SQL_Retail_Analytics_Project/Dataset/online_retail_clean.csv'
INTO TABLE online_retail_clean
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT COUNT(*) FROM online_retail_clean;

-- 1. What is the total revenue generated by the company?
--    Insight Purpose: Helps understand the overall scale of business operations
SELECT 
    ROUND(SUM(TotalAmount), 2) AS total_revenue
FROM online_retail_clean;


-- 2. How has revenue changed over the years?
SELECT 
    Year,
    ROUND(SUM(TotalAmount), 2) AS yearly_revenue
FROM online_retail_clean
GROUP BY Year
ORDER BY Year;


-- 3. Who are the top revenue-generating customers?
--    Insight Purpose: Identifies high-value customers contributing most to total revenue
SELECT
    CustomerID,
    ROUND(SUM(TotalAmount), 2) AS customer_revenue
FROM online_retail_clean
GROUP BY CustomerID
ORDER BY customer_revenue DESC
LIMIT 10;


-- 4. Which products generate the highest revenue?
--    Insight Purpose: Helps identify best-selling products for inventory and sales strategy
SELECT
    StockCode,
    Description,
    ROUND(SUM(TotalAmount), 2) AS product_revenue
FROM online_retail_clean
GROUP BY StockCode, Description
ORDER BY product_revenue DESC
LIMIT 10;


-- 5. Which countries contribute the most to total revenue?
--    Insight Purpose: Helps understand geographic market performance
SELECT
    Country,
    ROUND(SUM(TotalAmount), 2) AS country_revenue
FROM online_retail_clean
GROUP BY Country
ORDER BY country_revenue DESC
LIMIT 10;


-- 6. Calculate total revenue for each month
--    Purpose: Create a clean monthly revenue table
SELECT
    Year, Month, ROUND(SUM(TotalAmount), 2) AS monthly_revenue
FROM online_retail_clean
GROUP BY Year, Month
ORDER BY Year, Month;


-- 7. Average Order Value (AOV)
SELECT ROUND(SUM(TotalAmount) / COUNT(DISTINCT InvoiceNo), 2) AS avg_order_value
FROM online_retail_clean;


-- 8. CTE to calculate total revenue generated by each customer
--    Purpose: Create a reusable and clean revenue table for further analysis
WITH customer_revenue AS (
    SELECT
        CustomerID,
        ROUND(SUM(TotalAmount), 2) AS total_revenue
    FROM online_retail_clean
    GROUP BY CustomerID
)
-- Final output: list of customers ordered by revenue
SELECT
    CustomerID,
    total_revenue
FROM customer_revenue
ORDER BY total_revenue DESC
LIMIT 10;


-- 9. CTE to calculate yearly revenue per customer
--    Purpose: Prepare customer-level revenue data per year
WITH customer_yearly_revenue AS (
    SELECT Year, CustomerID, ROUND(SUM(TotalAmount), 2) AS yearly_revenue
    FROM online_retail_clean
    GROUP BY Year, CustomerID
)
SELECT * FROM customer_yearly_revenue
ORDER BY Year, yearly_revenue DESC;


-- 10. Rank customers based on revenue using window function
WITH customer_revenue AS (
    SELECT CustomerID, ROUND(SUM(TotalAmount), 2) AS total_revenue
    FROM online_retail_clean
    GROUP BY CustomerID
)
SELECT CustomerID, total_revenue,  RANK() OVER (ORDER BY total_revenue DESC) AS revenue_rank
FROM customer_revenue
ORDER BY revenue_rank
LIMIT 10;


-- 11. Compare RANK vs DENSE_RANK for customer revenue
-- Purpose: Understand ranking behavior when revenues are equal
WITH customer_revenue AS (
    SELECT CustomerID, ROUND(SUM(TotalAmount), 2) AS total_revenue
    FROM online_retail_clean
    GROUP BY CustomerID
)
SELECT CustomerID, total_revenue,
    RANK() OVER (ORDER BY total_revenue DESC) AS rank_position,
    DENSE_RANK() OVER (ORDER BY total_revenue DESC) AS dense_rank_position
FROM customer_revenue
ORDER BY total_revenue DESC
LIMIT 15;


-- 12. Month-over-Month revenue growth using LAG()
--     Purpose: Compare current month revenue with previous month
WITH monthly_revenue AS (
    SELECT Year, Month, ROUND(SUM(TotalAmount), 2) AS monthly_revenue
    FROM online_retail_clean
    GROUP BY Year, Month
)
SELECT Year, Month, monthly_revenue,
    -- Previous month's revenue
    LAG(monthly_revenue) OVER (ORDER BY Year, Month) AS previous_month_revenue,
    -- Month-over-Month growth
    ROUND(monthly_revenue - LAG(monthly_revenue) OVER (ORDER BY Year, Month),2) AS mom_growth
FROM monthly_revenue
ORDER BY Year, Month;


-- 13. Cumulative revenue using window function
--     Purpose: Track running total revenue over time
WITH monthly_revenue AS (
    SELECT Year, Month, ROUND(SUM(TotalAmount), 2) AS monthly_revenue
    FROM online_retail_clean
    GROUP BY Year, Month
)
SELECT Year, Month, monthly_revenue, ROUND(SUM(monthly_revenue) OVER 
(ORDER BY Year, Month ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), 2)
AS cumulative_revenue 
FROM monthly_revenue 
ORDER BY Year, Month;


-- 14. Rank customers within each year based on revenue
--     Purpose: Identify top customers year-wise
WITH customer_yearly_revenue AS (
    SELECT Year, CustomerID, ROUND(SUM(TotalAmount), 2) AS yearly_revenue
    FROM online_retail_clean
    GROUP BY Year, CustomerID
)
SELECT Year, CustomerID, yearly_revenue,
RANK() OVER (PARTITION BY Year ORDER BY yearly_revenue DESC) AS revenue_rank
FROM customer_yearly_revenue
ORDER BY Year, revenue_rank;


-- 15. Top 5 customers per year by revenue
WITH customer_yearly_revenue AS (
    SELECT Year, CustomerID, ROUND(SUM(TotalAmount), 2) AS yearly_revenue
    FROM online_retail_clean
    GROUP BY Year, CustomerID), 
    ranked_customers AS (SELECT Year, CustomerID, yearly_revenue, RANK()
    OVER (PARTITION BY Year ORDER BY yearly_revenue DESC) AS revenue_rank
    FROM customer_yearly_revenue
)
SELECT * FROM ranked_customers
WHERE revenue_rank <= 5
ORDER BY Year, revenue_rank;


-- 16. Customer segmentation based on total revenue
--     Purpose: Classify customers into High / Medium / Low value groups
WITH customer_revenue AS (
    SELECT CustomerID, ROUND(SUM(TotalAmount), 2) AS total_revenue
    FROM online_retail_clean
    GROUP BY CustomerID
)
SELECT CustomerID, total_revenue, CASE
        WHEN total_revenue >= 200000 THEN 'High Value'
        WHEN total_revenue >= 50000 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment
FROM customer_revenue
ORDER BY total_revenue DESC;


-- 17. Count of customers in each segment
WITH customer_revenue AS (
    SELECT CustomerID, ROUND(SUM(TotalAmount), 2) AS total_revenue
    FROM online_retail_clean
    GROUP BY CustomerID
)
SELECT CASE
        WHEN total_revenue >= 200000 THEN 'High Value'
        WHEN total_revenue >= 50000 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment, COUNT(*) AS number_of_customers
FROM customer_revenue
GROUP BY customer_segment;


--   Some other Analysis are as follows :- 

-- 18. Revenue contribution percentage by customer
--     Purpose: Understand how much each customer contributes to total revenue

WITH customer_revenue AS (
    SELECT CustomerID, ROUND(SUM(TotalAmount), 2) AS total_revenue
    FROM online_retail_clean
    GROUP BY CustomerID
)
SELECT CustomerID, total_revenue, ROUND(total_revenue / SUM(total_revenue) OVER () * 100,2)
AS revenue_contribution_pct
FROM customer_revenue
ORDER BY revenue_contribution_pct DESC
LIMIT 10;


-- 19. Customer segmentation using quartiles (NTILE)
-- Purpose: Segment customers based on lifetime value distribution
WITH customer_revenue AS (SELECT CustomerID, ROUND(SUM(TotalAmount), 2) AS total_revenue
    FROM online_retail_clean
    GROUP BY CustomerID
)
SELECT CustomerID, total_revenue, NTILE(4) OVER (ORDER BY total_revenue DESC) AS revenue_quartile
FROM customer_revenue
ORDER BY total_revenue DESC;


-- 20. Top-selling product in each country
--     Purpose: Identify best-performing product country-wise
WITH product_country_revenue AS (
    SELECT Country, StockCode, Description, ROUND(SUM(TotalAmount), 2) AS product_revenue
    FROM online_retail_clean
    GROUP BY Country, StockCode, Description), ranked_products AS 
(
    SELECT Country, StockCode, Description, product_revenue, RANK() OVER (PARTITION BY Country
	ORDER BY product_revenue DESC) AS country_rank
    FROM product_country_revenue
)
    SELECT Country, StockCode, Description, product_revenue
    FROM ranked_products
    WHERE country_rank = 1
    ORDER BY product_revenue DESC;































